### ISSUE TITLE
Support for allow-discards for dm-crypt possible?

### ISSUE THREAD

**Issue by capi** [TeamWin/android_device_oneplus_oneplus2#7]
I have a fully encrypted OnePlus 2, and I have the "feeling", that it doesn't get `fstrim`-ed on the `/data` partition. This is mostly expected, since this is information disclosure. `dm-crypt` supports `allow-discards` since some versions and I had hoped that I could call `fstrim` from TWRP.

While I can call `fstrim` on `/cache`, it fails on the (decrypted) `/data` with this message:
```
# fstrim -v /data
fstrim -v /data
fstrim: FITRIM: Operation not supported on transport endpoint
```

I _think_, this is an indication that the crypt-device was created without the `allow-discards` option, since the flash seems to support discard, since it works on `/cache`.

Any chance on enabling the `allow-discards` option for TWRP, so that people who really want it, can trim the encrypted /data?

**Comment by ghost** [comment]
I'll look into this issue soon

For now, boot android and run this (
su
mount -o remount,rw /system
fstrim -v /system
fstrim -v /data
fstrim -v /cache
fstrim -v /persist

Now reboot

**Comment by ghost** [comment]
fstrim binary is included in jrummy's busybox jus in case you're wondering
Alternatively mount data with the discard option

su
mount -o remount,discard /data #ext4 only

**Comment by ghost** [comment]
Hi I looked into this

It sadly doesn't seem possible as the images for data are not built when you run make recoveryimage

Your only option is to do so when booted into android with busybox

**Comment by capi** [comment]
Sad to hear, but not a huge problem. Thanks for looking into this!

**Comment by steadfasterX** [comment]
@anupritaisno1 what do you mean by "the images for data are not built" ? 
does this just mean the fstrim binary is not build and included in TWRP?

**Comment by ghost** [comment]
If I'm right android builds image files such as system.img, userdata.img, etc and then creates a similar filesystem on the device. It seems that these images are not built when using twrp. Likely due to the small recovery partition size

The fstrim binary is included but it can't trim encrypted volumes

**Comment by steadfasterX** [comment]
yea system.img etc will not be created when building twrp but I still don't understand why that would be needed to enable fstrim on encrypted partitions. what is the relationship between img files and fstrim?

**Comment by ghost** [comment]
That's the only place where the flag could be tbh. Do you have any device where fstrim is working?

**Comment by ghost** [comment]
I did a little test
Compile the ROM with the "quota" fsmgr flag for userdata
Compile bleeding edge twrp against nougat lineageos manifest
(Because nougat e2fsprogs doesn't support quota)
Twrp fails to run e2fsck with its built-in tools on /data

Now replace the boot.img with lineage-15.1 official's, still fails so the flag is in data and not controlled by the kernel

Slightly weird, wipe data and this time revert to an older unofficial lineage build, this time I just ran mka bootimage and didn't flash the whole ROM. This time around quota wasn't enabled even though it was specified in the fstab

This stuff makes me think that the images the build system builds do indeed have some kind of a relationship with how userdata partition is treated

I might be wrong though. I should research a bit more on this

**Comment by ghost** [comment]
Okay I'll do a little test. I'll try to compile lineageos with a kernel that supports the new file-based encryption that Google made. A port is available for angler so I could honestly just pick it from there. Once I'm up I'll have to add support to twrp for the same and test if fstrim actually works in file-based encryption mode. I've never tried file-based encryption though so it'll be something new to test

**Comment by steadfasterX** [comment]
afaik trim on encrypted userdata works fine on the LG G2

**Comment by ghost** [comment]
The even weirder part is that fstrim for a /cache partition formatted with f2fs works in twrp but doesn't work when booted into android

**Comment by ghost** [comment]
@steadfaster I'll take a look

Bear in mind that the device you're suggesting is slightly older so the code might not apply to our device

**Comment by ghost** [comment]
I just checked that device and there's nothing very specific that I can find out

**Comment by steadfasterX** [comment]
ok I got an answer: the guy who said it works on the LG g2 uses that one:

https://forum.xda-developers.com/lg-g2/development/twrp-twrp-2-8-0-0-kernel-f2fs-tools-t2898705

so not the official

**Comment by ghost** [comment]
Update: I'm currently working on getting this to work. No idea if I'll be successful

I've gone through all of the code now and maybe we can get this to work

**Comment by ghost** [comment]
Another update: I'm not sure if I'm really doing it correctly here but if it works we can consider adding this to official

https://github.com/GlassROM-devices/android_kernel_oneplus_msm8994/compare/323807e95fa3...132bef90e777

Only time will tell if this works

Also I'd like to request the person who created this issue to reopen it
